### ISSUE TITLE
make sure everyone using github/mdbooks to see content

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_ecosystem#1]
# preferred

- everyone has github account
- everyone knows how to get content to own system
    - everyone knows how to update/push content
- everyone know basics of writing markdown docs (visual studio code or macdown)

# worst case

- edits on github itself

**Comment by sabrinasadik** [comment]
Internally: ok
Externally: pushing them to upload their own information, otherwise we fill in the info
