### ISSUE TITLE
this website home page 

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_ecosystem#2]
- why this
- what brings us together
- some clipart/design elements in the same style as io website (or copy)
- header linking back to threefold.io

**Comment by despiegk** [comment]
maybe same header as TF.io

**Comment by Vilnite** [comment]
Work file for CIA landing page:
https://docs.google.com/document/d/180KidXuNYT3921FoU0ieTq4B-ZuRIELs7oosI6t3nxg/edit
