### ISSUE TITLE
fix markdown files to look decent [master]

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/www_threefold_ecosystem#23]
![image](https://user-images.githubusercontent.com/64129/80703136-85305280-8ae2-11ea-85d3-803a86b44a9d.png)

![image](https://user-images.githubusercontent.com/64129/80703161-8feae780-8ae2-11ea-9cbc-d2cffeca8289.png)

this doesn't look good at all, people should be able to define their experience and a nicely formatted markdown. 

**don't edit** "roadmap" or "data" section

**Comment by PeterNashaat** [comment]
Fixes merged to master branch
