### ISSUE TITLE
content what is wisdom council, ... 

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/www_threefold_ecosystem#5]
- why
- what are requirements for person to be there
- the responsibilities of this councile

https://github.com/threefoldfoundation/www_threefold_ecosystem/blob/master/preparation/grant_acceptance_doc.md

**Comment by sabrinasadik** [comment]
@despiegk we need content for this

**Comment by Karoline888** [comment]
Still waiting for content and clarity to reach out.
Having received the list about the people who are considered to be in the wisdom council.
